### PR TITLE
[READY] - init term-apply application

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description

Init the `term-apply` application which provides a way for new applicant engineers to apply to work @ nebulaworks

Process of applying is as simple as sshing and filling out the form presented via your ssh session:
```
ssh <github_user>@sshapply.nebulaworks.com
```

`scp` your resume to the server as well:

```
scp -P 23234 <resume>.pdf <github_user>@sshapply.nebulaworks.com:resume.pdf
```
> Note: your ssh key needs to be associated with the same github_user your are passing

## Tests
- Unit tests pass:

```
$ make test
go clean -testcache
go test --race ./...
?       github.com/nebulaworks/orion/apps/term-apply    [no test files]
ok      github.com/nebulaworks/orion/apps/term-apply/pkg/applicant      0.032s
?       github.com/nebulaworks/orion/apps/term-apply/pkg/auth   [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/server [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/transfer       [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/ui     [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/version        [no test files]
```

- Application builds binary `term-apply`

```
$ make build
go build -ldflags="-X '"github.com/nebulaworks/orion/apps/term-apply/pkg/version".Commit=$(git rev-parse HEAD)' -X '"github.com/nebulaworks/orion/apps/term-apply/pkg/version".BuildTime=$(date +'%Y-%m-%d_%T')'" -o term-apply

[nix-shell:~/workspace/orion/apps/term-apply]$ ./term-apply 
2022/04/01 16:23:32 
Build Info:
===========
commit:      0779c4100bfa209ec7d8551b9f481a7d0d69204d
build time:  2022-04-01_16:23:25

2022/04/01 16:23:32 TA_HOST not found, defaulting to '0.0.0.0'
2022/04/01 16:23:32 bad ports string  or TA_PORT not found, defaulting to 23234
2022/04/01 16:23:32 TA_UPLOAD_DIR not found, defaulting to './uploads'
2022/04/01 16:23:32 TA_DATAFILE not found, defaulting to 'applicants.csv'
2022/04/01 16:23:32 Importing existing resumes from ./uploads
2022/04/01 16:23:32 found sarcasticadmin-resume.pdf
2022/04/01 16:23:32 Starting SSH server on 0.0.0.0:23234
```

- Confirmed that service is running and able to process applicants on `sshapply.nebulaworks.com`

### CODE REVIEW

**Comment by jshcmpbll** [comment]
```
go clean -testcache
go test --race ./...
?       github.com/nebulaworks/orion/apps/term-apply    [no test files]
ok      github.com/nebulaworks/orion/apps/term-apply/pkg/applicant      0.017s
?       github.com/nebulaworks/orion/apps/term-apply/pkg/auth   [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/server [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/transfer       [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/ui     [no test files]
?       github.com/nebulaworks/orion/apps/term-apply/pkg/version        [no test files]
```

**Review by jshcmpbll — APPROVED** [review]
LGTM ran test and manually tested application

**Comment by sarcasticadmin** [comment]
@jshcmpbll thanks!

**Review by mathplusyou — APPROVED** [review]
LGTM!

**Pull request merged**
